// version: 1
using System.Collections.Generic;
using System;
public static class GenUnityTypes
{
    [XLua.LuaCallCSharp] public static IEnumerable<Type> LuaCallCSharp { get { return List; } }
    [XLua.CSharpCallLua] public static List<Type> CSharpCallLua { get { return GenConfig.CSharpCallLua(List); } }
    private static System.Type[] List = {

typeof(UnityEngine.AccelerationEvent),
// typeof(UnityEngine.AddComponentMenu),
typeof(UnityEngine.AnchoredJoint2D),
// typeof(UnityEngine.AndroidInput),
// typeof(UnityEngine.AndroidJavaClass),
// typeof(UnityEngine.AndroidJavaException),
// typeof(UnityEngine.AndroidJavaObject),
// typeof(UnityEngine.AndroidJavaProxy),
// typeof(UnityEngine.AndroidJNI),
// typeof(UnityEngine.AndroidJNIHelper),
typeof(UnityEngine.Animation),
typeof(UnityEngine.AnimationClip),
typeof(UnityEngine.AnimationCurve),
typeof(UnityEngine.AnimationEvent),
typeof(UnityEngine.AnimationState),
typeof(UnityEngine.Animator),
typeof(UnityEngine.AnimatorClipInfo),
typeof(UnityEngine.AnimatorControllerParameter),
typeof(UnityEngine.AnimatorOverrideController),
typeof(UnityEngine.AnimatorStateInfo),
typeof(UnityEngine.AnimatorTransitionInfo),
typeof(UnityEngine.AnimatorUtility),
typeof(UnityEngine.Application),
typeof(UnityEngine.AreaEffector2D),
// typeof(UnityEngine.AssemblyIsEditorAssembly),
typeof(UnityEngine.AssetBundle),
// typeof(UnityEngine.AssetBundleCreateRequest),
typeof(UnityEngine.AssetBundleManifest),
// typeof(UnityEngine.AssetBundleRecompressOperation),
// typeof(UnityEngine.AssetBundleRequest),
// typeof(UnityEngine.AsyncOperation),
typeof(UnityEngine.AudioBehaviour),
typeof(UnityEngine.AudioChorusFilter),
typeof(UnityEngine.AudioClip),
typeof(UnityEngine.AudioConfiguration),
typeof(UnityEngine.AudioDistortionFilter),
typeof(UnityEngine.AudioEchoFilter),
typeof(UnityEngine.AudioHighPassFilter),
typeof(UnityEngine.AudioListener),
typeof(UnityEngine.AudioLowPassFilter),
typeof(UnityEngine.AudioRenderer),
typeof(UnityEngine.AudioReverbFilter),
typeof(UnityEngine.AudioReverbZone),
typeof(UnityEngine.AudioSettings),
typeof(UnityEngine.AudioSource),
typeof(UnityEngine.Avatar),
typeof(UnityEngine.AvatarBuilder),
typeof(UnityEngine.AvatarMask),
// typeof(UnityEngine.BeforeRenderOrderAttribute),
typeof(UnityEngine.Behaviour),
typeof(UnityEngine.BillboardAsset),
typeof(UnityEngine.BillboardRenderer),
typeof(UnityEngine.BoneWeight),
typeof(UnityEngine.BoneWeight1),
typeof(UnityEngine.BoundingSphere),
typeof(UnityEngine.Bounds),
typeof(UnityEngine.BoundsInt),
// typeof(UnityEngine.BoundsInt.PositionEnumerator),
typeof(UnityEngine.BoxcastCommand),
typeof(UnityEngine.BoxCollider),
typeof(UnityEngine.BoxCollider2D),
typeof(UnityEngine.BuildCompression),
typeof(UnityEngine.BuoyancyEffector2D),
typeof(UnityEngine.Cache),
typeof(UnityEngine.CachedAssetBundle),
typeof(UnityEngine.Caching),
typeof(UnityEngine.Camera),
typeof(UnityEngine.Camera.GateFitParameters),
typeof(UnityEngine.Canvas),
typeof(UnityEngine.CanvasGroup),
typeof(UnityEngine.CanvasRenderer),
typeof(UnityEngine.CapsulecastCommand),
typeof(UnityEngine.CapsuleCollider),
typeof(UnityEngine.CapsuleCollider2D),
typeof(UnityEngine.CharacterController),
typeof(UnityEngine.CharacterInfo),
typeof(UnityEngine.CharacterJoint),
typeof(UnityEngine.CircleCollider2D),
typeof(UnityEngine.Cloth),
typeof(UnityEngine.ClothSkinningCoefficient),
typeof(UnityEngine.ClothSphereColliderPair),
// typeof(UnityEngine.ClusterInput),
// typeof(UnityEngine.ClusterNetwork),
typeof(UnityEngine.Collider),
typeof(UnityEngine.Collider2D),
typeof(UnityEngine.ColliderDistance2D),
typeof(UnityEngine.Collision),
typeof(UnityEngine.Collision2D),
typeof(UnityEngine.Color),
typeof(UnityEngine.Color32),
// typeof(UnityEngine.ColorUsageAttribute),
typeof(UnityEngine.ColorUtility),
typeof(UnityEngine.CombineInstance),
typeof(UnityEngine.Compass),
typeof(UnityEngine.Component),
typeof(UnityEngine.CompositeCollider2D),
typeof(UnityEngine.ComputeBuffer),
typeof(UnityEngine.ComputeShader),
typeof(UnityEngine.ConfigurableJoint),
typeof(UnityEngine.ConstantForce),
typeof(UnityEngine.ConstantForce2D),
typeof(UnityEngine.ContactFilter2D),
typeof(UnityEngine.ContactPoint),
typeof(UnityEngine.ContactPoint2D),
// typeof(UnityEngine.ContextMenu),
// typeof(UnityEngine.ContextMenuItemAttribute),
typeof(UnityEngine.ControllerColliderHit),
typeof(UnityEngine.Coroutine),
typeof(UnityEngine.CrashReport),
// typeof(UnityEngine.CreateAssetMenuAttribute),
typeof(UnityEngine.Cubemap),
typeof(UnityEngine.CubemapArray),
typeof(UnityEngine.CullingGroup),
typeof(UnityEngine.CullingGroupEvent),
// typeof(UnityEngine.Cursor),
// typeof(UnityEngine.CustomGridBrushAttribute),
typeof(UnityEngine.CustomRenderTexture),
typeof(UnityEngine.CustomRenderTextureUpdateZone),
typeof(UnityEngine.CustomYieldInstruction),
typeof(UnityEngine.Debug),
typeof(UnityEngine.DefaultExecutionOrder),
// typeof(UnityEngine.DelayedAttribute),
// typeof(UnityEngine.DetailPrototype),
// typeof(UnityEngine.DisallowMultipleComponent),
typeof(UnityEngine.Display),
typeof(UnityEngine.DistanceJoint2D),
typeof(UnityEngine.DrivenRectTransformTracker),
typeof(UnityEngine.DynamicGI),
typeof(UnityEngine.EdgeCollider2D),
typeof(UnityEngine.Effector2D),
typeof(UnityEngine.Event),
// typeof(UnityEngine.EventProvider),
// typeof(UnityEngine.ExcludeFromObjectFactoryAttribute),
// typeof(UnityEngine.ExcludeFromPresetAttribute),
typeof(UnityEngine.ExecuteAlways),
// typeof(UnityEngine.ExecuteInEditMode),
// typeof(UnityEngine.ExitGUIException),
typeof(UnityEngine.ExposedPropertyResolver),
// typeof(UnityEngine.ExposedReference<>),
typeof(UnityEngine.FixedJoint),
typeof(UnityEngine.FixedJoint2D),
typeof(UnityEngine.Flare),
typeof(UnityEngine.FlareLayer),
typeof(UnityEngine.Font),
typeof(UnityEngine.FrameTiming),
typeof(UnityEngine.FrameTimingManager),
typeof(UnityEngine.FrictionJoint2D),
typeof(UnityEngine.FrustumPlanes),
typeof(UnityEngine.GameObject),
typeof(UnityEngine.GeometryUtility),
// typeof(UnityEngine.Gizmos),
typeof(UnityEngine.GL),
typeof(UnityEngine.Gradient),
typeof(UnityEngine.GradientAlphaKey),
typeof(UnityEngine.GradientColorKey),
// typeof(UnityEngine.GradientUsageAttribute),
typeof(UnityEngine.Graphics),
typeof(UnityEngine.GraphicsBuffer),
typeof(UnityEngine.Grid),
typeof(UnityEngine.GridBrushBase),
typeof(UnityEngine.GridLayout),
// typeof(UnityEngine.GUI),
// typeof(UnityEngine.GUI.ClipScope),
// typeof(UnityEngine.GUI.GroupScope),
// typeof(UnityEngine.GUI.Scope),
// typeof(UnityEngine.GUI.ScrollViewScope),
// typeof(UnityEngine.GUIContent),
// typeof(UnityEngine.GUIElement),
// typeof(UnityEngine.GUILayout),
// typeof(UnityEngine.GUILayout.AreaScope),
// typeof(UnityEngine.GUILayout.HorizontalScope),
// typeof(UnityEngine.GUILayout.ScrollViewScope),
// typeof(UnityEngine.GUILayout.VerticalScope),
// typeof(UnityEngine.GUILayoutOption),
// typeof(UnityEngine.GUILayoutUtility),
// typeof(UnityEngine.GUISettings),
// typeof(UnityEngine.GUISkin),
// typeof(UnityEngine.GUIStyle),
// typeof(UnityEngine.GUIStyleState),
// typeof(UnityEngine.GUITargetAttribute),
// typeof(UnityEngine.GUIUtility),
typeof(UnityEngine.Gyroscope),
// typeof(UnityEngine.Handheld),
typeof(UnityEngine.Hash128),
typeof(UnityEngine.HashUnsafeUtilities),
typeof(UnityEngine.HashUtilities),
// typeof(UnityEngine.HeaderAttribute),
// typeof(UnityEngine.HelpURLAttribute),
// typeof(UnityEngine.HideInInspector),
typeof(UnityEngine.HingeJoint),
typeof(UnityEngine.HingeJoint2D),
typeof(UnityEngine.HumanBone),
typeof(UnityEngine.HumanDescription),
typeof(UnityEngine.HumanLimit),
typeof(UnityEngine.HumanPose),
typeof(UnityEngine.HumanPoseHandler),
typeof(UnityEngine.HumanTrait),
typeof(UnityEngine.ImageConversion),
typeof(UnityEngine.ImageEffectAfterScale),
typeof(UnityEngine.ImageEffectAllowedInSceneView),
typeof(UnityEngine.ImageEffectOpaque),
typeof(UnityEngine.ImageEffectTransformsToLDR),
typeof(UnityEngine.ImageEffectUsesCommandBuffer),
typeof(UnityEngine.Input),
// typeof(UnityEngine.InspectorNameAttribute),
typeof(UnityEngine.IntegratedSubsystem),
// typeof(UnityEngine.IntegratedSubsystem<>),
typeof(UnityEngine.IntegratedSubsystemDescriptor),
// typeof(UnityEngine.IntegratedSubsystemDescriptor<>),
// typeof(UnityEngine.iPhoneSettings),
// typeof(UnityEngine.iPhoneUtils),
typeof(UnityEngine.Joint),
typeof(UnityEngine.Joint2D),
typeof(UnityEngine.JointAngleLimits2D),
typeof(UnityEngine.JointDrive),
typeof(UnityEngine.JointLimits),
typeof(UnityEngine.JointMotor),
typeof(UnityEngine.JointMotor2D),
typeof(UnityEngine.JointSpring),
typeof(UnityEngine.JointSuspension2D),
typeof(UnityEngine.JointTranslationLimits2D),
typeof(UnityEngine.JsonUtility),
// typeof(UnityEngine.jvalue),
typeof(UnityEngine.Keyframe),
typeof(UnityEngine.LayerMask),
typeof(UnityEngine.LensFlare),
typeof(UnityEngine.Light),
typeof(UnityEngine.LightBakingOutput),
typeof(UnityEngine.LightmapData),
typeof(UnityEngine.LightmapSettings),
typeof(UnityEngine.LightProbeGroup),
typeof(UnityEngine.LightProbeProxyVolume),
typeof(UnityEngine.LightProbes),
typeof(UnityEngine.LineRenderer),
typeof(UnityEngine.LineUtility),
typeof(UnityEngine.LocalizationAsset),
typeof(UnityEngine.LocationInfo),
typeof(UnityEngine.LocationService),
typeof(UnityEngine.LOD),
typeof(UnityEngine.LODGroup),
typeof(UnityEngine.Logger),
typeof(UnityEngine.MatchTargetWeightMask),
typeof(UnityEngine.Material),
typeof(UnityEngine.MaterialPropertyBlock),
typeof(UnityEngine.Mathf),
typeof(UnityEngine.Matrix4x4),
typeof(UnityEngine.Mesh),
typeof(UnityEngine.MeshCollider),
typeof(UnityEngine.MeshFilter),
typeof(UnityEngine.MeshRenderer),
typeof(UnityEngine.Microphone),
// typeof(UnityEngine.MinAttribute),
typeof(UnityEngine.MissingComponentException),
typeof(UnityEngine.MissingReferenceException),
typeof(UnityEngine.MonoBehaviour),
// typeof(UnityEngine.Motion),
// typeof(UnityEngine.MultilineAttribute),
typeof(UnityEngine.Object),
typeof(UnityEngine.OcclusionArea),
typeof(UnityEngine.OcclusionPortal),
typeof(UnityEngine.ParticleCollisionEvent),
typeof(UnityEngine.ParticlePhysicsExtensions),
typeof(UnityEngine.ParticleSystem),
typeof(UnityEngine.ParticleSystem.Burst),
typeof(UnityEngine.ParticleSystem.CollisionModule),
typeof(UnityEngine.ParticleSystem.ColorBySpeedModule),
typeof(UnityEngine.ParticleSystem.ColorOverLifetimeModule),
typeof(UnityEngine.ParticleSystem.CustomDataModule),
typeof(UnityEngine.ParticleSystem.EmissionModule),
typeof(UnityEngine.ParticleSystem.EmitParams),
typeof(UnityEngine.ParticleSystem.ExternalForcesModule),
typeof(UnityEngine.ParticleSystem.ForceOverLifetimeModule),
typeof(UnityEngine.ParticleSystem.InheritVelocityModule),
typeof(UnityEngine.ParticleSystem.LightsModule),
typeof(UnityEngine.ParticleSystem.LimitVelocityOverLifetimeModule),
typeof(UnityEngine.ParticleSystem.MainModule),
typeof(UnityEngine.ParticleSystem.MinMaxCurve),
typeof(UnityEngine.ParticleSystem.MinMaxGradient),
typeof(UnityEngine.ParticleSystem.NoiseModule),
typeof(UnityEngine.ParticleSystem.Particle),
typeof(UnityEngine.ParticleSystem.RotationBySpeedModule),
typeof(UnityEngine.ParticleSystem.RotationOverLifetimeModule),
typeof(UnityEngine.ParticleSystem.ShapeModule),
typeof(UnityEngine.ParticleSystem.SizeBySpeedModule),
typeof(UnityEngine.ParticleSystem.SizeOverLifetimeModule),
typeof(UnityEngine.ParticleSystem.SubEmittersModule),
typeof(UnityEngine.ParticleSystem.TextureSheetAnimationModule),
typeof(UnityEngine.ParticleSystem.TrailModule),
typeof(UnityEngine.ParticleSystem.TriggerModule),
typeof(UnityEngine.ParticleSystem.VelocityOverLifetimeModule),
typeof(UnityEngine.ParticleSystemForceField),
typeof(UnityEngine.ParticleSystemRenderer),
typeof(UnityEngine.PatchExtents),
typeof(UnityEngine.PhysicMaterial),
typeof(UnityEngine.Physics),
typeof(UnityEngine.Physics2D),
typeof(UnityEngine.PhysicsJobOptions2D),
typeof(UnityEngine.PhysicsMaterial2D),
typeof(UnityEngine.PhysicsScene),
typeof(UnityEngine.PhysicsScene2D),
typeof(UnityEngine.PhysicsSceneExtensions),
typeof(UnityEngine.PhysicsSceneExtensions2D),
typeof(UnityEngine.PhysicsUpdateBehaviour2D),
// typeof(UnityEngine.Ping),
typeof(UnityEngine.Plane),
typeof(UnityEngine.PlatformEffector2D),
typeof(UnityEngine.PlayerPrefs),
typeof(UnityEngine.PlayerPrefsException),
typeof(UnityEngine.PointEffector2D),
typeof(UnityEngine.PolygonCollider2D),
typeof(UnityEngine.Pose),
typeof(UnityEngine.PreferBinarySerialization),
typeof(UnityEngine.Projector),
// typeof(UnityEngine.PropertyAttribute),
typeof(UnityEngine.PropertyName),
typeof(UnityEngine.QualitySettings),
typeof(UnityEngine.Quaternion),
typeof(UnityEngine.Random),
typeof(UnityEngine.Random.State),
// typeof(UnityEngine.RangeAttribute),
typeof(UnityEngine.RangeInt),
typeof(UnityEngine.Ray),
typeof(UnityEngine.Ray2D),
typeof(UnityEngine.RaycastCommand),
typeof(UnityEngine.RaycastHit),
typeof(UnityEngine.RaycastHit2D),
typeof(UnityEngine.Rect),
typeof(UnityEngine.RectInt),
// typeof(UnityEngine.RectInt.PositionEnumerator),
typeof(UnityEngine.RectOffset),
typeof(UnityEngine.RectTransform),
typeof(UnityEngine.RectTransformUtility),
typeof(UnityEngine.ReflectionProbe),
typeof(UnityEngine.RelativeJoint2D),
typeof(UnityEngine.RemoteConfigSettings),
typeof(UnityEngine.RemoteSettings),
typeof(UnityEngine.RenderBuffer),
typeof(UnityEngine.Renderer),
typeof(UnityEngine.RendererExtensions),
typeof(UnityEngine.RenderSettings),
typeof(UnityEngine.RenderTargetSetup),
typeof(UnityEngine.RenderTexture),
typeof(UnityEngine.RenderTextureDescriptor),
// typeof(UnityEngine.RequireComponent),
typeof(UnityEngine.Resolution),
// typeof(UnityEngine.ResourceRequest),
typeof(UnityEngine.Resources),
typeof(UnityEngine.Rigidbody),
typeof(UnityEngine.Rigidbody2D),
typeof(UnityEngine.RuntimeAnimatorController),
// typeof(UnityEngine.RuntimeInitializeOnLoadMethodAttribute),
typeof(UnityEngine.ScalableBufferManager),
typeof(UnityEngine.Screen),
typeof(UnityEngine.ScreenCapture),
typeof(UnityEngine.ScriptableObject),
typeof(UnityEngine.SecondarySpriteTexture),
typeof(UnityEngine.Security),
// typeof(UnityEngine.SelectionBaseAttribute),
// typeof(UnityEngine.SerializeField),
typeof(UnityEngine.Shader),
// typeof(UnityEngine.ShaderVariantCollection),
// typeof(UnityEngine.ShaderVariantCollection.ShaderVariant),
// typeof(UnityEngine.SharedBetweenAnimatorsAttribute),
typeof(UnityEngine.SkeletonBone),
typeof(UnityEngine.SkinnedMeshRenderer),
typeof(UnityEngine.Skybox),
typeof(UnityEngine.SleepTimeout),
typeof(UnityEngine.SliderJoint2D),
// typeof(UnityEngine.Social),
typeof(UnityEngine.SoftJointLimit),
typeof(UnityEngine.SoftJointLimitSpring),
typeof(UnityEngine.SortingLayer),
// typeof(UnityEngine.SpaceAttribute),
typeof(UnityEngine.SparseTexture),
typeof(UnityEngine.SpherecastCommand),
typeof(UnityEngine.SphereCollider),
// typeof(UnityEngine.SplatPrototype),
typeof(UnityEngine.SpringJoint),
typeof(UnityEngine.SpringJoint2D),
typeof(UnityEngine.Sprite),
typeof(UnityEngine.SpriteMask),
typeof(UnityEngine.SpriteRenderer),
typeof(UnityEngine.StackTraceUtility),
typeof(UnityEngine.StateMachineBehaviour),
typeof(UnityEngine.StaticBatchingUtility),
typeof(UnityEngine.StreamingController),
typeof(UnityEngine.Subsystem),
// typeof(UnityEngine.Subsystem<>),
typeof(UnityEngine.SubsystemDescriptor),
// typeof(UnityEngine.SubsystemDescriptor<>),
typeof(UnityEngine.SubsystemManager),
typeof(UnityEngine.SurfaceEffector2D),
typeof(UnityEngine.SystemInfo),
typeof(UnityEngine.TargetJoint2D),
// typeof(UnityEngine.Terrain),
// typeof(UnityEngine.TerrainCollider),
// typeof(UnityEngine.TerrainData),
// typeof(UnityEngine.TerrainExtensions),
// typeof(UnityEngine.TerrainLayer),
// typeof(UnityEngine.TextAreaAttribute),
typeof(UnityEngine.TextAsset),
// typeof(UnityEngine.TextEditor),
typeof(UnityEngine.TextGenerationSettings),
// typeof(UnityEngine.TextGenerator),
typeof(UnityEngine.TextMesh),
typeof(UnityEngine.Texture),
typeof(UnityEngine.Texture2D),
typeof(UnityEngine.Texture2DArray),
typeof(UnityEngine.Texture3D),
typeof(UnityEngine.Time),
// typeof(UnityEngine.TooltipAttribute),
typeof(UnityEngine.Touch),
// typeof(UnityEngine.TouchScreenKeyboard),
// typeof(UnityEngine.TrackedReference),
typeof(UnityEngine.TrailRenderer),
typeof(UnityEngine.Transform),
// typeof(UnityEngine.Tree),
// typeof(UnityEngine.TreeInstance),
// typeof(UnityEngine.TreePrototype),
// typeof(UnityEngine.Types),
typeof(UnityEngine.UI.AnimationTriggers),
typeof(UnityEngine.UI.AspectRatioFitter),
typeof(UnityEngine.UI.BaseMeshEffect),
typeof(UnityEngine.UI.Button),
typeof(UnityEngine.UI.Button.ButtonClickedEvent),
typeof(UnityEngine.UI.CanvasScaler),
typeof(UnityEngine.UI.CanvasUpdateRegistry),
typeof(UnityEngine.UI.ClipperRegistry),
typeof(UnityEngine.UI.Clipping),
typeof(UnityEngine.UI.ColorBlock),
typeof(UnityEngine.UI.ContentSizeFitter),
typeof(UnityEngine.UI.DefaultControls),
typeof(UnityEngine.UI.DefaultControls.Resources),
typeof(UnityEngine.UI.Dropdown),
typeof(UnityEngine.UI.Dropdown.DropdownEvent),
typeof(UnityEngine.UI.Dropdown.OptionData),
typeof(UnityEngine.UI.Dropdown.OptionDataList),
typeof(UnityEngine.UI.FontData),
typeof(UnityEngine.UI.FontUpdateTracker),
typeof(UnityEngine.UI.Graphic),
typeof(UnityEngine.UI.GraphicRaycaster),
// typeof(UnityEngine.UI.GraphicRebuildTracker),
typeof(UnityEngine.UI.GraphicRegistry),
typeof(UnityEngine.UI.GridLayoutGroup),
typeof(UnityEngine.UI.HorizontalLayoutGroup),
typeof(UnityEngine.UI.HorizontalOrVerticalLayoutGroup),
typeof(UnityEngine.UI.Image),
typeof(UnityEngine.UI.InputField),
typeof(UnityEngine.UI.InputField.OnChangeEvent),
typeof(UnityEngine.UI.InputField.SubmitEvent),
typeof(UnityEngine.UI.LayoutElement),
typeof(UnityEngine.UI.LayoutGroup),
typeof(UnityEngine.UI.LayoutRebuilder),
typeof(UnityEngine.UI.LayoutUtility),
typeof(UnityEngine.UI.Mask),
typeof(UnityEngine.UI.MaskableGraphic),
typeof(UnityEngine.UI.MaskableGraphic.CullStateChangedEvent),
typeof(UnityEngine.UI.MaskUtilities),
typeof(UnityEngine.UI.Navigation),
typeof(UnityEngine.UI.Outline),
typeof(UnityEngine.UI.PositionAsUV1),
typeof(UnityEngine.UI.RawImage),
typeof(UnityEngine.UI.RectMask2D),
typeof(UnityEngine.UI.Scrollbar),
typeof(UnityEngine.UI.Scrollbar.ScrollEvent),
typeof(UnityEngine.UI.ScrollRect),
typeof(UnityEngine.UI.ScrollRect.ScrollRectEvent),
typeof(UnityEngine.UI.Selectable),
typeof(UnityEngine.UI.Shadow),
typeof(UnityEngine.UI.Slider),
typeof(UnityEngine.UI.Slider.SliderEvent),
typeof(UnityEngine.UI.SpriteState),
typeof(UnityEngine.UI.StencilMaterial),
typeof(UnityEngine.UI.Text),
typeof(UnityEngine.UI.Toggle),
typeof(UnityEngine.UI.Toggle.ToggleEvent),
typeof(UnityEngine.UI.ToggleGroup),
typeof(UnityEngine.UI.VertexHelper),
typeof(UnityEngine.UI.VerticalLayoutGroup),
typeof(UnityEngine.UICharInfo),
typeof(UnityEngine.UILineInfo),
typeof(UnityEngine.UISystemProfilerApi),
typeof(UnityEngine.UIVertex),
typeof(UnityEngine.UnassignedReferenceException),
// typeof(UnityEngine.UnityAPICompatibilityVersionAttribute),
typeof(UnityEngine.UnityEventQueueSystem),
typeof(UnityEngine.UnityException),
typeof(UnityEngine.Vector2),
typeof(UnityEngine.Vector2Int),
typeof(UnityEngine.Vector3),
typeof(UnityEngine.Vector3Int),
typeof(UnityEngine.Vector4),
typeof(UnityEngine.WaitForEndOfFrame),
typeof(UnityEngine.WaitForFixedUpdate),
typeof(UnityEngine.WaitForSeconds),
typeof(UnityEngine.WaitForSecondsRealtime),
typeof(UnityEngine.WaitUntil),
typeof(UnityEngine.WaitWhile),
typeof(UnityEngine.WebCamDevice),
typeof(UnityEngine.WebCamTexture),
typeof(UnityEngine.WheelCollider),
typeof(UnityEngine.WheelFrictionCurve),
typeof(UnityEngine.WheelHit),
typeof(UnityEngine.WheelJoint2D),
typeof(UnityEngine.WindZone),
// typeof(UnityEngine.WWWAudioExtensions),
typeof(UnityEngine.WWWForm),
typeof(UnityEngine.YieldInstruction),

    };
}
